def battleKeywordsImportant
    return [
        "rainstorm",
        "sunshine",
        "sandstorm",
        "hail",
        "total Ring Eclipse",
        "total eclipse",
        "Ring Eclipse",
        "eclipse",
        "full moon",
        "moonglow",
        "Heavy Rain",
        "Harsh Sunlight",
        "Star Storm",
        "Ice Age",
        "Blood Moon",
        "Strong Winds",
        "burning spikes",
        "severely burning",
        "severely burned",
        "severely burns",
        "severe burn",
        "burning",
        "burned",
        "burns",
        "burn",
        "frozen spikes",
        "severely frostbiting",
        "severely frostbitten",
        "severely frostbites",
        "severe frostbite",
        "frostbiting",
        "frostbitten",
        "frostbites",
        "frostbite",
        "severely numbing",
        "severely numbed",
        "severely numbs",
        "severe numb",
        "numbing",
        "numbed",
        "numbs",
        "numb",
        "poison spikes",
        "poisoning",
        "poisoned",
        "poisons",
        "poison",
        "leeching",
        "leeched",
        "leeches",
        "leech",
        "dizzying",
        "dizzied",
        "dizzies",
        "dizzy",
        "waterlogging",
        "waterlogged",
        "waterlogs",
        "waterlog",
        "asleep",
        "sleep",
        "drowsy",
        "cursing",
        "cursed",
        "curse",
        "blind",
        "blinds",
        "blindness",
        "fracturing",
        "fractured",
        "fracture",
        "jinxing",
        "jinxed",
        "jinx",
        "disabled",
        "disables",
        "disable",
        "tormented",
        "maximizes",
        "maximize",
        "minimized",
        "minimizes",
        "minimize",
        "minimizing",
        "aqua ring",
        "recoil",
        "flinching",
        "flinched",
        "flinch",
        "random added effects",
        "random added effect",
        "trapping",
        "trapped",
        "traps",
        "trap",
        "gravity",
        "trick room",
        "puzzle room",
        "odd room",
        "polarized room",
        "insight room",
        "emotion room",
        "willful room",
        "rooms",
        "room",
        "tailwind",
        "weather",
        "random critical hits",
        "random critical hit",
        "critical hit chance",
        "critical hits",
        "critical hit",
        "screens",
        "invulnerable",
        "clothing",
        "Grey Mist",
        "stockpiles",
        "stockpile",
        "hazards",
        "hazard",
        "offensive",
        "defensive",
        "coins",
        "money",
        "spread",
        "multi-hits",
        "multi-hit",
        "rampaging",
        "rampages",
        "rampage",
        "charging",
        "charges",
        "charge",
        "exhausted",
        "exhausting",
        "energized",
        "energize",
        "substitutes",
        "substitute",
        "binding",
        "binds",
        "bind",
        "hidden",
        "foretelling",
        "foretells",
        "foretell",
        "foretold",
        "barred",
        "bar",
        "mental",
        "shrinks",
        "shrinking",
        "sugar rush",
        "self-destructing",
    ]
end

def battleKeywordsImportantCaseSensitive
    return [
        "Sp. Atk",
        "Special Attack",
        "Attack",
        "Sp. Def",
        "Special Defense",
        "Defense",
        "Speed",
        "Accuracy",
        "Evasion",
        "Frost Spikes",
        "Flame Spikes",
        "Poison Spikes",
        "Spikes",
    ]
end

def battleKeywordsUnimportant
    return [
        "twice",
        "doubles",
        "double",
        "doubled",
        "three times",
        "four times",
        "five times",
        "half",
        "one third",
        "two thirds",
        "one quarter",
        "three quarters",
        "one fifth",
        "1/4th",
        "1/5th",
        "1/6th",
        "1/8th",
        "1/10th",
        "1/12th",
        "1/16th",
        "1/20th",
        "all stats",
        "all its stats",
    ]
end

def battleKeywordsUnimportantCaseSensitive
    return [
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
        "twenty",
    ]
end

def moveTagKeywords
    return [
        "biting",
        "bite",
        "punching",
        "punch",
        "kicking",
        "kick",
        "slice",
        "dancing",
        "dance",
        "sound-based",
        "sound",
        "wind-based",
        "wind",
        "light-based",
        "light",
        "pulse",
    ]
end

def addBattleKeywordHighlighting(description, isAbility: false)
    # Highlight very important words in red
    importantColorTag = getSkinColor(nil, 2, darkMode?, true)
    battleKeywordsImportant.each do |keyword|
        description = description.gsub(/\b(#{keyword})\b/i,"#{importantColorTag}\\1</c3>")
    end
    battleKeywordsImportantCaseSensitive.each do |keyword|
        description = description.gsub(/\b(#{keyword})\b/,"#{importantColorTag}\\1</c3>")
    end

    # Outline less important keywords in blue
    unimportantColorTag = getSkinColor(nil, 13, darkMode?, true)
    battleKeywordsUnimportant.each do |keyword|
        description = description.gsub(/\b(#{keyword})\b/i,"#{unimportantColorTag}\\1</c3>")
    end
    battleKeywordsUnimportantCaseSensitive.each do |keyword|
        description = description.gsub(/\b(#{keyword})\b/,"#{unimportantColorTag}\\1</c3>")
    end

    # Outline move tags in ability descriptions in green (not case sensitive)
    if isAbility
        moveTagKeywords.each do |tag|
            description = description.gsub(/\b(#{tag})\b/i,"#{importantColorTag}\\1</c3>")
        end
    end

    return description
end